spring:
  application:
    name: hanteo
  datasource:
    url: jdbc:mysql://127.0.0.1:9172/hanteo?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: gilbert
    password: 1234

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
server:
  port: 9090
